### ISSUE TITLE
API Keys - Env vars

### ISSUE THREAD

**Issue by tejasmanohar** [anishathalye/remembrall#2]
https://github.com/anishathalye/remembrall/blob/master/rt/videoproc.py#L49

Keep API Keys in environment variables.

**Comment by anishathalye** [comment]
Yeah, we know.

Eh, it's not a big deal, we don't use the account anymore, and it's only a free account (anyone can obtain one here: https://rekognition.com/user/price). It's not even my account, so I can't generate new keys.

**Comment by tejasmanohar** [comment]
Alright :+1:
